### ISSUE TITLE
Automated builds/continuous deployment infrastructure for s2i-base

### ISSUE THREAD

**Issue by jawnsy** [sclorg/s2i-base-container#107]
The latest release of [`openshift/base-centos7`](https://hub.docker.com/r/openshift/base-centos7/tags/) on Docker Hub was pushed (at current time of writing) 21 days ago.  The underlying image, [`centos:7`](https://hub.docker.com/r/library/centos/tags/7/) appears to have last been pushed 15 days ago, which means that our latest image is at least a few days out of date.

Are there plans for some sort of automated build/continuous deployment infrastructure for `s2i-base`?  For example, Docker Hub has an [automated build feature](https://docs.docker.com/docker-hub/builds/) which can rebuild/push `openshift/base-centos7` whenever `centos:7` changes, so that we can get the latest security fixes.  Alternatively, if we can automatically push from CentOS' Container Pipeline to DockerHub, that may be preferable.  Either way, I think we need to ensure we propagate updates from the `centos` base image down to all of the S2I Builder Images that depend on this base image.

**Comment by bparees** [comment]
> The latest release of openshift/base-centos7 on Docker Hub was pushed (at current time of writing) 21 days ago.

we periodically rebuild+push all the images regardless of whether the repo has changed, so changes to centos7 will be automatically be picked up periodically.  (we also automatically build+push when the repo changes).

> Are there plans for some sort of automated build/continuous deployment infrastructure for s2i-base?

there is one already.

> For example, Docker Hub has an automated build feature which can rebuild/push openshift/base-centos7 whenever centos:7 changes, so that we can get the latest security fixes. 

the automated build feature is limited in several ways that prevent us from using it for maintaining these images.
