### ISSUE TITLE
fix-permission optimization

### ISSUE THREAD

**Issue by cata86** [sclorg/s2i-base-container#108]
fix-permission is very slow.
instead of
```
#!/bin/sh
# Fix permissions on the given directory to allow group read/write of 
# regular files and execute of directories.
find $1 -exec chgrp 0 {} \;
find $1 -exec chmod g+rw {} \;
find $1 -type d -exec chmod g+x {} +
```

I tried with
```
#!/bin/sh
# Fix permissions on the given directory to allow group read/write of
# regular files and execute of directories.
chgrp -R 0 $1;
chmod -R g+rw $1;
find $1 -type d -exec chmod g+x {} +
```
it is faster at least 100x
both scripts produce the same result.

**Comment by bparees** [comment]
chgrp -R/chmod -R does not handle symlinked directories in the way we desire.

**Comment by cata86** [comment]
In our environment fix-permission takes 10minutes to finish.

**Comment by bparees** [comment]
i don't deny it's an issue, i'm just saying this isn't a valid way to solve it unfortunately because it introduces new problems.

**Comment by cata86** [comment]
In a normal project 
sh-4.2$ ls -lR . | grep ^l                                                                                              
have no output
do you think that some npm package can create symlinked directories ?

**Comment by bparees** [comment]
1) those commands are run against the entire source input, not just npm package dirs
2) this image is used for more than nodejs images.

**Comment by cata86** [comment]
Is this better?
```
#!/bin/sh
# Fix permissions on the given directory to allow group read/write of
# regular files and execute of directories.
chgrp -R 0 $1;
find -L $1 -xtype l -exec chgrp 0 {} \;
chmod -R g+rw $1;
find -L $1 -xtype l -exec chmod g+rw {} \;
find $1 -type d -exec chmod g+x {} +
```

**Comment by bparees** [comment]
that looks like it should be ok...

**Comment by cata86** [comment]
When you want you can accept the pull request
