### ISSUE TITLE
Warning messages when fix-permissions run on a symlink.

### ISSUE THREAD

**Issue by GrahamDumpleton** [sclorg/s2i-base-container#112]
In the Python S2I builder, the directories which ``fix-permissions`` is run on can include symlinks which point to somewhere outside of the directory used for the application. The directories/files being pointed at can be owned by root.

The result of this is that ``fix-permissions`` generates lots of warnings of type:

```
chgrp: changing group of '/opt/app-root/include/python2.7': Operation not permitted
chgrp: changing group of '/opt/app-root/lib/python2.7/UserDict.py': Operation not permitted
chgrp: changing group of '/opt/app-root/lib/python2.7/_abcoll.py': Operation not permitted
...
chmod: changing permissions of '/opt/app-root/include/python2.7': Operation not permitted
chmod: changing permissions of '/opt/app-root/lib/python2.7/UserDict.py': Operation not permitted
chmod: changing permissions of '/opt/app-root/lib/python2.7/_abcoll.py': Operation not permitted
chmod: changing permissions of '/opt/app-root/lib/python2.7/_weakrefset.py': Operation not permitted
```

This is because ``chgrp`` and ``chmod`` act on what the symlink points to and not the symlink and thus fail.

This was warned about in:

* https://github.com/sclorg/s2i-python-container/pull/159

but nothing was done about it before PR was merged.

Bumping this to base image for addressing.

The only known workaround would be to use the ``-f`` option with ``chmod`` and ``chgrp`` so it ignores the failures. It is not known though whether that would mask any other problems.

Only other solution would be stop trying to use shell commands for this and write a custom C/go program which does a more intelligent traversal of the directory hierarchy to fix up permissions and ownership.

**Comment by GrahamDumpleton** [comment]
The ``fix-permissions`` as written suffers other problems as well. A summary of all the problems are as follows.

1: Due to:

```
find -L $1 -xtype l -exec chgrp 0 {} \;
find -L $1 -xtype l -exec chmod g+rw {} \;
```

the script is trying to update the permissions of directories or files which are the target of symlinks. This is what causes the errors such as:

```
chgrp: changing group of '/opt/app-root/include/python2.7': Operation not permitted
chgrp: changing group of '/opt/app-root/lib/python2.7/UserDict.py': Operation not permitted
chgrp: changing group of '/opt/app-root/lib/python2.7/_abcoll.py': Operation not permitted
...
chmod: changing permissions of '/opt/app-root/include/python2.7': Operation not permitted
chmod: changing permissions of '/opt/app-root/lib/python2.7/UserDict.py': Operation not permitted
chmod: changing permissions of '/opt/app-root/lib/python2.7/_abcoll.py': Operation not permitted
chmod: changing permissions of '/opt/app-root/lib/python2.7/_weakrefset.py': Operation not permitted
```

when the target of the symlink is in a location outside of the directory hierarchy the permissions are being fixed on, and that location is owned by a user/group that the user running ``fix-permissions`` cannot modify.

It isn't even obvious why these two lines were even added in the first place. The change is:

* https://github.com/sclorg/s2i-base-container/commit/420a3c3bd9743121af022fa6401c27e41ac99dcf

but the comment doesn't explain why.

There are two cases to consider.

The first is where the target is in the same directory hierarchy that ``fix-permissions`` was being run on. In this case there was no need to have these lines as when the physical files were traversed in the same directory hierarchy, their permissions would have been fixed up then.

The second is where the target is not in the same directory hierarchy, but as stated above, where is the justification for trying to update the permissions on the target in that case. If something in a different location needed to have permissions updated, the ``fix-permissions`` should have been separately run on that other location.

2: Because only ``g+rw`` is performed on files, if a file was actually a program and marked as executable by owner, ie., ``u+x``, but was missing ``g+x``, then the execute bit wouldn't be propagated across to group and so when run as an assigned user ID and relying on group root access, the application wouldn't be able to run the program and would fail.

3: The current ``fix-permissions`` script will run ``chmod`` and ``chgrp`` to update permissions and group, even if the directories and files have the desired permissions set already. This is bad, because even if the same and no change is actually required, under ``docker build``, this will cause a new copy of the files to be made in the current image layer. This means you are bloating out the size of the image unnecessarily. Where files are large, this is not good. This is especially an issue in the Python S2I builder where a Python virtual environment is created and ``fix-permissions`` gets run over the complete Python virtual environment again during the S2I build phase after Python packages are installed.

The current shell script and use of ``find``, ``chmod`` and ``chgrp`` commands is always going to a clumsy way of doing this. A custom C/Go program is probably going to be the only way to get exactly what is required and still perform well.

An example C program to do what is required is as follows.

```
#include <stdio.h>
#include <fts.h>
#include <unistd.h>
#include <stdlib.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <string.h>
#include <errno.h>

void fix(const char* path, struct stat* info)
{
    /*
     * We only call chown()/chmod() if a change is required. If we don't
     * do this and always perform the call, then a new copy of the file
     * will be made in a new image layer even if nothing changed.
     */

    mode_t mode = info->st_mode;

    /*
     * Propagate the mode bits from the user to the group so group has
     * same rights as the user, this includes the ability to access a
     * directory or execute a file.
     */

    if (mode & S_IRUSR)
        mode |= S_IRGRP;

    if (mode & S_IWUSR)
        mode |= S_IWGRP;

    if (mode & S_IXUSR)
        mode |= S_IXGRP;

    if (mode != info->st_mode)
    {
        if (chmod(path, mode) == -1)
        {
            fprintf(stderr, "WARNING: changing permissions of '%s': %s\n",
                    path, strerror(errno));
        }
    }

    /* Ensure the group is set to root (gid=0). */

    if (info->st_gid != 0)
    {
        if (chown(path, -1, 0) == -1)
        {
            fprintf(stderr, "WARNING: changing group of '%s': %s\n",
                    path, strerror(errno));
        }
    }
}

int main(int argc, char** argv)
{
    FTS* root = NULL;
    FTSENT *node = NULL;

    struct stat info;

    if (argc < 2)
    {
        fprintf(stderr, "USAGE: %s <path-spec>\n", argv[0]);

        exit(EXIT_FAILURE);
    }

    /*
     * Process the root directory first as it will not be returned
     * when we traverse the directory tree below. In the case of the
     * root directory, if the path we are given is a symbolic link,
     * then we process the target of the link. In practice we should
     * probably never be given a path that is a symlink, instead the
     * target of the symlink should be given if that was what was
     * really intended.
     */

    if (stat(argv[1], &info) == -1 || !S_ISDIR(info.st_mode))
    {
        fprintf(stderr, "ERROR: Invalid root directory %s\n", argv[1]);

        exit(EXIT_FAILURE);
    }

    fix(argv[1], &info);

    /* Now traverse the directory hierarchy. */

    root = fts_open(&argv[1], FTS_PHYSICAL|FTS_NOCHDIR, NULL);

    if (root != NULL)
    {
        while((node = fts_read(root)) != NULL)
        {
            /*
             * We ignore any symbolic links as it is the ownership and
             * permissions of what is pointed at that is important not
             * that of the symbolic link. If the target of the symlink
             * is in the same directory hierarchy then it will be picked
             * up when traverse the physical file. If the target of the
             * symlink was outside of the directory hierarchy, then we
             * should not be updating it anyway.
             */

            switch (node->fts_info)
            {
                case FTS_D :
                case FTS_F :
                    fix(node->fts_path, node->fts_statp);

                    break;

                default:
                    break;
            }
        }

        fts_close(root);
    }

    return 0;
}
```

Because this base image installs ``gcc``, you can just copy the ``fix-permissions.c`` file into the image and then run the compiled on it to produce ``/usr/bin/fix-permissions``.

Do note that this current C code is my interpretation of what should be done, it differs from what is currently down in a number of ways.

1: It only updates permissions or group if there is a change required. This is to avoid making copies of files in new layer when nothing had to change.

2: It ignores symlinks. I can't see that a need for it to follow symlinks has been demonstrated. That past change to do that had no justification for the change in the comment. If the target was within the same directory hierarchy then it will be fixed when the physical file is encountered when traversing the directories. If the target was outside of the directory hierarchy, there isn't a reason an attempt should be made to change it. A separate invocation of ``fix-permissions`` should be run if other locations need to also be fixed up.

3: Rather than just assume ``g+x`` for directories and ``u+rw`` for files is enough, instead, if any of ``rwx`` is set for the owner, it will also set that bit for the group. This way if a file has ``u+rwx,g-rwx``, the result would be ``u+rwx,g+rwx`` and the ability to execute a program would pass across to group and wouldn't fail when run by an application.

The only issue this strategy brings up is what if the original files had permissions of ``u+r,g+r,o+r``. In some respects that ``g+w`` is not added is correct, as ``u+w`` wasn't present in the first place, but by not adding ``g+w``, then you can't use ``oc rsync`` to update files which were ``u+r`` only. But then, if someone had run the same image using ``anyuid`` role applied, then ``oc rsync`` would have failed anyway since it wasn't writable to the user. It can be argued that if ``oc rsync`` ability was important, then files shouldn't have been created as read only to begin with.

**Comment by GrahamDumpleton** [comment]
BTW, the current C program assumes it will be given a path to a directory, not a file. If this is supposed to be able to accept a path to a file instead, a slight change would need to be made.

**Comment by bparees** [comment]
regarding the symlink following behavior, from the original fix:
https://github.com/sclorg/s2i-base-container/commit/921c12de429051680114a60880dd10d6e123cdfd

https://github.com/sclorg/s2i-base-container/commit/921c12de429051680114a60880dd10d6e123cdfd#commitcomment-20005605

unfortunately i'm unable to track down the original issue report so i can't recall the exact use case that lead to this, but we didn't do it for the heck of it (as you can see, the original script didn't handle it properly, so it was reported as an issue) and if you're considering changing the behavior you are risking breaking backwards compatibility in all the images that depend on this script.

**Comment by GrahamDumpleton** [comment]
Option would be, update a file (not directory) which is target of a symlink if the current user has appropriate privileges, or not issue a warning if it doesn't and would fail. Would that cover it?

**Comment by bparees** [comment]
> Option would be, update a file (not directory) which is target of a symlink if the current user has appropriate privileges, or not issue a warning if it doesn't and would fail. Would that cover it?

making it a warning and not a failure if the permissions can't be updated sounds reasonable.

**Comment by GrahamDumpleton** [comment]
The ``fix-permissions`` script as it is now doesn't cause a failure, but it is the message which is frightening people and they keep asking what it means. The idea is to not issue any message at all if it cannot update what the symlink points at. This gets rids of the current message that people keep asking about.

**Comment by GrahamDumpleton** [comment]
Okay, new version of ``fix-permissions.c`` code.

On the issue of warnings, current thinking is why we output any at all. In this version they are off by default but can be enabled using a ``-w`` option. Have also got a ``-d`` option so outputs debug to validate what it is doing. When S2I debug level is enabled is that by chance passed through in an environment variable. If it is, could perhaps trigger these options at some debug level automatically.

This version handles the argument passed being a file, as well as a directory. It is also possible to pass more than one path. This may be useful if doing this from a ``Dockerfile`` and avoid multiple executions of the command. If a directory contains a symlink to a file, will now apply changes to target of the symlink. For backward compatibility, also now always setting ``g+w`` regardless of whether had ``u+w``.

```
#include <stdio.h>
#include <fts.h>
#include <unistd.h>
#include <stdlib.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <string.h>
#include <errno.h>

void fixup(const char* path, struct stat* info, int warn, int debug)
{
    mode_t mode = info->st_mode;

    if (debug)
        fprintf(stderr, "fixup(path=%s)\n", path);

    /*
     * Propagate the mode bits from the user to the group so group has
     * same rights as the user, this includes the ability to access a
     * directory or execute a file.
     */

    if (mode & S_IRUSR)
        mode |= S_IRGRP;

    if (mode & S_IWUSR)
        mode |= S_IWGRP;

    if (mode & S_IXUSR)
        mode |= S_IXGRP;

    /*
     * For backward compatibility with what has been done in past, but
     * also to ensure that 'oc rsync' can always update files in an image
     * when run as an assigned user ID, relying on group access via root
     * user, we always override permissions and make file or directory
     * writable to group. This does mean that if a file or directory was
     * originally not writable by the owner that is now writable by group.
     */

    mode |= S_IWGRP;

    /*
     * Update the permissions. We only call chmod() if a change is
     * required. If we don't have this check and always perform the call,
     * then a new copy of the file will be made in a new image layer even
     * if nothing changed.
     */

    if (mode != info->st_mode)
    {
        if (debug)
            fprintf(stderr, "chmod(path=%s, mode=0%o)\n", path, mode);

        if (chmod(path, mode) == -1 && warn)
        {
            fprintf(stderr, "WARNING: changing permissions of '%s': %s\n",
                    path, strerror(errno));
        }
    }

    /*
     * Ensure the group is set to root (gid=0). We only call chown() if
     * a change is required. If we don't do this and always perform the
     * call, then a new copy of the file will be made in a new image
     * layer even if nothing changed.
     */

    if (info->st_gid != 0)
    {
        if (debug)
            fprintf(stderr, "chown(path=%s, uid=-1, gid=0)\n", path);

        if (chown(path, -1, 0) == -1 && warn)
        {
            fprintf(stderr, "WARNING: changing group of '%s': %s\n",
                    path, strerror(errno));
        }
    }
}

void traverse(char* path, int warn, int debug)
{
    char* const path_argv[] = { path, NULL };

    FTS* root = NULL;
    FTSENT *node = NULL;

    struct stat info;

    if (debug)
        fprintf(stderr, "traverse(path=%s, warn=%d)\n", path, warn);

    /* Check we have been given a valid path. Stop now if not. */

    if (stat(path, &info) == -1)
    {
        fprintf(stderr, "ERROR: Invalid path %s\n", path);

        return;
    }

    /*
     * If initial path is not a directory process it and stop. Note that
     * in this case we have used stat(), so always operating on the target
     * if a symbolic link.
     */

    if (!S_ISDIR(info.st_mode))
    {
        fixup(path, &info, warn, debug);

        return;
    }

    /*
     * Now traverse the directory hierarchy. If the path we are given
     * is a symbolic link, then we process the target of the link. In
     * practice we should probably never be given a path that is a
     * symbolic link, instead the target of the symlink should be given
     * if that was what was really intended.
     */

    root = fts_open(path_argv, FTS_PHYSICAL|FTS_COMFOLLOW|FTS_NOCHDIR, NULL);

    if (root != NULL)
    {
        while((node = fts_read(root)) != NULL)
        {
            switch (node->fts_info)
            {
                case FTS_D :
                case FTS_F :
                    fixup(node->fts_path, node->fts_statp, warn, debug);

                    break;

                case FTS_SL:
                    /*
                     * If we find a symbolic link within the directory
                     * hierarchy we need to run stat() on the target of
                     * the link. If the target is a directory or cannot
                     * be resolved we ignore it. Otherwise we apply
                     * fixes to the target of the link. This is done to
                     * maintain backward compatibility for certain use
                     * cases.
                     */

                    if (stat(node->fts_path, &info) == -1)
                        break;

                    if (S_ISDIR(info.st_mode))
                        break;

                    fixup(node->fts_path, &info, warn, debug);

                    break;

                default:
                    break;
            }
        }

        fts_close(root);
    }
}

int main(int argc, char** argv)
{
    int warn = 0;
    int debug = 0;

    if (argc < 2)
    {
        fprintf(stderr, "USAGE: %s [-w] [-d] <path> ...\n", argv[0]);

        exit(EXIT_FAILURE);
    }

    while (--argc)
    {
        argv++;

        if (strcmp(*argv, "-w") == 0)
        {
            warn = 1;

            continue;
        }

        if (strcmp(*argv, "-d") == 0)
        {
            debug = 1;

            continue;
        }

        traverse(*argv, warn, debug);
    }

    return 0;
}
```

**Comment by GrahamDumpleton** [comment]
From https://github.com/sclorg/s2i-python-container/issues/178 @bparees said:

"""

The current behavior:

1. recursively chmods/chgrps all files/dirs in the provided path. symlinks are effectively ignored (thus as are the targets of those symlinks)
2. all symlinks are followed to their target(whether a directory or a file) and a non-recursive chmod/chgrp is performed on them.

so give a dir "/tmp/foo" containing "/tmp/foo/file1" and a symlink "b" that points to /tmp/foo, with this logic, /tmp/foo will be modifed, /tmp/fool/file1 will not be modified.

the good news is that means no recursive symlink loops. the bad news is it's probably not really correct in that /tmp/foo/file1 probably should be modified, if we're trying to be at all consistent (perhaps don't follow it if it's a symlink, but at least modify it). (in otherwords, step 2 should follow the symlink and invoke a recursive chmod/chgrp on the target. since recursive chmod/chgrp doesn't follow symlinks, this is safe from an infinite loop perspective).

"""

Based on that I offer up a new version of C code for doing this. It should do the following:

1. Recursively go through a directory hierarchy and for physical directories and files, fixup permissions etc.
2. When it encounters a symlink and the symlink points at a file, fixup permissions etc on the target of the symlink.
3. When it encounters a symlink and the symlink points at a directory, if we haven't reached limit on how many directory symlinks we follow, start over but on the directory which is the target of the symlink. In following the symlink to the directory, you get one closer to the limit.

What this means is that for first level directory tree, all directory and file (non symlink), plus files which are targets of symlinks, have permissions etc fixed. For the second level directory tree after following a symlink to a directory, where the recursion limit is 1 (default), then all directory and file (non symlink), plus files which are targets of symlinks, have permissions etc fixed, but you do not follow symlinks any further to directories from second level directory tree.

By default the recursion limit is 1, but you could increase this if there was a need. There is also a command line argument to override it.

```
#include <stdio.h>
#include <fts.h>
#include <unistd.h>
#include <stdlib.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <string.h>
#include <errno.h>

void fixup(const char* path, struct stat* info, int warn, int debug, int indent)
{
    mode_t mode = info->st_mode;

    if (debug)
    {
        int n = indent;

        while (n--)
            fprintf(stderr, "  ");

        fprintf(stderr, "fixup(path=%s)\n", path);
    }

    /*
     * Propagate the mode bits from the user to the group so group has
     * same rights as the user, this includes the ability to access a
     * directory or execute a file.
     */

    if (mode & S_IRUSR)
        mode |= S_IRGRP;

    if (mode & S_IWUSR)
        mode |= S_IWGRP;

    if (mode & S_IXUSR)
        mode |= S_IXGRP;

    /*
     * For backward compatibility with what has been done in past, but
     * also to ensure that 'oc rsync' can always update files in an image
     * when run as an assigned user ID, relying on group access via root
     * user, we always override permissions and make file or directory
     * writable to group. This does mean that if a file or directory was
     * originally not writable by the owner that is now writable by group.
     */

    mode |= S_IWGRP;

    /*
     * Update the permissions. We only call chmod() if a change is
     * required. If we don't have this check and always perform the call,
     * then a new copy of the file will be made in a new image layer even
     * if nothing changed.
     */

    if (mode != info->st_mode)
    {
        if (debug)
        {
            int n = indent;

            while (n--)
                fprintf(stderr, "  ");

            fprintf(stderr, "chmod(path=%s, mode=0%o)\n", path, mode);
        }

        if (chmod(path, mode) == -1 && warn)
        {
            fprintf(stderr, "WARNING: changing permissions of '%s': %s\n",
                    path, strerror(errno));
        }
    }

    /*
     * Ensure the group is set to root (gid=0). We only call chown() if
     * a change is required. If we don't do this and always perform the
     * call, then a new copy of the file will be made in a new image
     * layer even if nothing changed.
     */

    if (info->st_gid != 0)
    {
        if (debug)
            fprintf(stderr, "chown(path=%s, uid=-1, gid=0)\n", path);

        if (chown(path, -1, 0) == -1 && warn)
        {
            fprintf(stderr, "WARNING: changing group of '%s': %s\n",
                    path, strerror(errno));
        }
    }
}

void traverse(char* path, int warn, int debug, int levels, int indent)
{
    char* const path_argv[] = { path, NULL };

    FTS* root = NULL;
    FTSENT *node = NULL;

    struct stat info;

    if (debug) {
        int n = indent;

        while (n--)
            fprintf(stderr, "  ");

        fprintf(stderr, "traverse(path=%s, levels=%d)\n", path, levels);
    }

    /* Check we have been given a valid path. Stop now if not. */

    if (stat(path, &info) == -1)
    {
        fprintf(stderr, "ERROR: Invalid path %s\n", path);

        return;
    }

    /*
     * If initial path is not a directory process it and stop. Note that
     * in this case we have used stat(), so always operating on the target
     * if a symbolic link.
     */

    if (!S_ISDIR(info.st_mode))
    {
        fixup(path, &info, warn, debug, indent);

        return;
    }

    /*
     * Now traverse the directory hierarchy. If the path we are given
     * is a symbolic link, then we process the target of the link. In
     * practice we should probably never be given a path that is a
     * symbolic link, instead the target of the symlink should be given
     * if that was what was really intended.
     */

    root = fts_open(path_argv, FTS_PHYSICAL|FTS_COMFOLLOW|FTS_NOCHDIR, NULL);

    if (root != NULL)
    {
        while((node = fts_read(root)) != NULL)
        {
            switch (node->fts_info) 
            {
                case FTS_D :
                case FTS_F :
                    fixup(node->fts_path, node->fts_statp, warn, debug, indent);

                    break;

                case FTS_SL:
                    /*
                     * If we find a symbolic link within the directory
                     * hierarchy we need to run stat() on the target of
                     * the link. If the target cannot be resolved we
                     * ignore it. If it is a directory we recursively
                     * traverse into it unless we have reached the limit
                     * on the number of levels to visit. If it is not a
                     * directory we apply fixes to the target of the link.
                     */

                    if (stat(node->fts_path, &info) == -1)
                        break;
                    
                    if (S_ISDIR(info.st_mode))
                    {
                        if (levels > 0)
                            traverse(node->fts_path, warn, debug, levels-1, indent+1);

                        break;
                    }

                    fixup(node->fts_path, &info, warn, debug, indent);

                    break;

                default:
                    break;
            }
        }

        fts_close(root);
    }
}

int main(int argc, char** argv)
{
    int warn = 0;
    int debug = 0;
    int levels = 1;

    if (argc < 2)
    {
        fprintf(stderr, "USAGE: %s [-w|--warnings] [-d|--debug] [--levels n] <path> ...\n", argv[0]);

        exit(EXIT_FAILURE);
    }

    while (--argc)
    {
        argv++;

        if (strcmp(*argv, "-w") == 0 || strcmp(*argv, "--warnings") == 0)
        {
            warn = 1;

            continue;
        }

        if (strcmp(*argv, "-d") == 0 || strcmp(*argv, "--debug") == 0)
        {
            debug = 1;

            continue;
        }

        if (strcmp(*argv, "--levels") == 0)
        {
            if (--argc)
                levels = atoi(*++argv);

            continue;
        }

        traverse(*argv, warn, debug, levels, 0);
    }

    return 0;
}
```

**Comment by omron93** [comment]
Or another solution:
```
find $1 \! -gid 0 -exec chgrp 0 {} +
find $1 \! -perm /g+rw -exec chmod g+rw {} +
#find $1 -perm /u+x -a \! -perm /g+x -exec chmod g+x {} +
find $1 -type d \! -perm /g+x -exec chmod g+x {} +
```

`find -L` can be used to process links to directories recursively.

**Comment by hhorak** [comment]
I'm not a big fan of solving this issue in C, because it would add a huge piece of code to be maintained, which does not seem to be worth it. With sore combination of @omron93's improvements and #120 changes I think we should be happy enough. There is obviously some level of risk of hiding some issues, but I don't see that as a big problem.

**Comment by omron93** [comment]
I've read through all PRs and issues related to this again. And ...

> The current behavior:
>1. recursively chmods/chgrps all files/dirs in the provided path. symlinks are effectively ignored (thus as are the targets of those symlinks)
>2. all symlinks are followed to their target(whether a directory or a file) and a non-recursive chmod/chgrp is performed on them.

`find -L $1 -xtype l` finds also links from symlinked directories.

So for example `fix-permissions x` 
```
y
x
├── file -> ../y
└── lib -> /usr/lib
```

Point 2. also changes all symlinks in `/usr/lib`. @bparees Is this what "the current behavior" should do? (instead of fixing permissions only of file `y` and directory `/usr/lib`)
I know that prevent current behavior is necessary, but IMPOV this is very misleading.

**Comment by bparees** [comment]
>  @bparees Is this what "the current behavior" should do? 
> (instead of fixing permissions only of file y and directory /usr/lib)

well i think it's clear that changing the permissions on the contents in /usr/lib is desirable (and is the current behavior).  Is your question specifically around how symlinks that reside in /usr/lib are treated?  (that the symlink itself is being chmod'd)?

**Comment by omron93** [comment]
> well i think it's clear that changing the permissions on the contents in /usr/lib is desirable

Well, it is questionable :-)

> (and is the current behavior). Is your question specifically around how symlinks that reside in /usr/lib are treated?

It is not current behavior! For example `chgrp -R x` does not changes files in `/usr/lib`. Then `find -L x -xtype l -exec chgrp 0 {} \;` changes group of `/usr/lib` itself and run chgrp only on symlinks in `/usr/lib` and changes group of its targets.
So only some unclear subset of files in `/usr/lib` is changed - this seems misleading to me and that is what my question was about.

**Comment by bparees** [comment]
> Well, it is questionable :-)

ok fair enough.  it is desirable in that bugs were filed against us because it wasn't happening, thus we introduced logic to make it happen.

> So only some unclear subset of files in /usr/lib is changed - this seems misleading to me and that is what my question was about.

if the new logic changes more files than the current logic does, that's probably ok.  if it changes fewer, that's probably not ok (per my first comment about bugs being reported because it wasn't changing those files, though i have to admit it seems likely to be a bit of an edge case and could conceivably be handled by a custom assemble script)

**Comment by GrahamDumpleton** [comment]
What is the full contents of the ``fix-permissions`` script you are currently proposing? Somewhere back in time a comment was made about performance concerns of successive calls to ``find`` to do fixups as separate steps. I have have some images which are probably a good candidate whether this is still going to be a problem. Need to see some actual times for running what is proposed.

**Comment by omron93** [comment]
> What is the full contents of the fix-permissions script you are currently proposing?

In https://github.com/sclorg/s2i-base-container/pull/120 :

```
find -L "$1" \! -gid 0 -exec chgrp 0 {} +
find -L "$1" \! -perm /g+rw -exec chmod g+rw {} +
find -L "$1" -perm /u+x -a \! -perm /g+x -exec chmod g+x {} +
find -L "$1" -type d \! -perm /g+x -exec chmod g+x {} +
```

> if the new logic changes more files than the current logic does, that's probably ok

On the other hand this can bring more `Permission denied` errors.

@bparees @GrahamDumpleton Is the new implementation OK?

> Somewhere back in time a comment was made about performance concerns of successive calls to find to do fixups as separate steps. I have have some images which are probably a good candidate whether this is still going to be a problem. Need to see some actual times for running what is proposed.

It would be great to have it tested. Thanks.

**Comment by bparees** [comment]
> On the other hand this can bring more Permission denied errors.

we need to mask the permission denied errors, i've gotten a couple complaints just this week about how ugly the current ones that show up in the python builds are :(

I don't think it's really a problem if we mask them, the net affect of a failed chmod/chrp is that the user may not have permission to edit the file in the container, which is really just for hot deploy purposes.  And it should be immediately obvious why they can't edit the file (and if we couldn't chmod it, there's not much we can do about it w/o updating the image itself).

**Comment by omron93** [comment]
> We need to mask the permission denied errors, i've gotten a couple complaints just this week about how ugly the current ones that show up in the python builds are :(
> I don't think it's really a problem if we mask them, the net affect of a failed chmod/chrp is that the user may not have permission to edit the file in the container, which is really just for hot deploy purposes.

Well, I don't think that masking error messages instead of solving why they appeared is a best way.

But decision is yours.

**Comment by bparees** [comment]
On May 4, 2017 08:30, "Marek Skalický" <notifications@github.com> wrote:

We need to mask the permission denied errors, i've gotten a couple
complaints just this week about how ugly the current ones that show up in
the python builds are :(
I don't think it's really a problem if we mask them, the net affect of a
failed chmod/chrp is that the user may not have permission to edit the file
in the container, which is really just for hot deploy purposes.

Well, I don't think that masking error messages instead of solving why they
appeared is a best way.

But decision is yours.


How do you plan to ensure they can never occur?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/sclorg/s2i-base-container/issues/112#issuecomment-299171183>,
or mute the thread

**Comment by omron93** [comment]
> How do you plan to ensure they can never occur?

It is not possible to ensure it for all user inputs - but also it is not possible to be sure that masked error messages won't cause troubles.

IMPOV problem is with "default" content which is in images and produces errors - in python case the virtual environment in `/opt/app-root/`.

It would be possible not to see these errors by "fixing permissions" only of files owned by current UID (`find ... -uid $(id -u) ...` - not needed for `root`). Or not to follow symlinks outside of `$1` or `$HOME`.

**Comment by thesteve0** [comment]
Why is this still not fixed? This showed up on the keynote stage for summit. It shows up in all my workshops.

I have to explain to the class this is a problem with our SCL image not their code
It makes us look like amateurs.
I don't understand how this can be allowed to persist for so long

It happened to me just yesterday in front of a class of 27 students. 

I know I have not added anything technically but the fact that this remains unfixed is really causing problems for all public facing work when we try to show how great S2I is for python (and other) devs.

**Comment by thesteve0** [comment]
When do we think this will roll out into the new SCL image?

**Comment by omron93** [comment]
@pkubatrh ?

**Comment by pkubatrh** [comment]
>When do we think this will roll out into the new SCL image?

Generally changes from upstream repositories are propagated to the (RHEL) images whenever a new base rhel image is released and all of the layered images are rebuilt on top of it.
So to answer the question - the next time an updated version of the s2i-base image is released it will contain this fix.
Not sure if the CentOS images are using a different workflow for this.

**Comment by omron93** [comment]
> Not sure if the CentOS images are using a different workflow for this.

CentOS based images are built after code is merged in github. So `centos/s2i-base-centos7` should contain this fix already.

**Comment by GrahamDumpleton** [comment]
The update CentOS image is available, but the change made does not actually appear to fix the problem. Was the change used on assumption it would work, after last prompting from Steve, or was it visually verified that it does solve the problem on builds for Python that were known to expose the problem?

Situation where I am seeing it still not helping is in example Python application used in OpenShift Katacoda environment. Can jump on learn.openshift.com and run 'Deploying from Application Source' scenario. Getting in running container after started, it looks to be new ``fix-permisions``, but logs for build still show the errors/warnings.

**Comment by pkubatrh** [comment]
>Was the change used on assumption it would work, after last prompting from Steve, or was it visually verified that it does solve the problem on builds for Python that were known to expose the problem?

Yes, before merging I have re-run and checked our CI tests which had the issue before.

Unfortunately, it seems https://github.com/sclorg/s2i-base-container/pull/125/ reintroduced the warnings by fixing another issue with the find and chmod calls. Reopening.

**Comment by omron93** [comment]
>The update CentOS image is available, but the change made does not actually appear to fix the problem. 

You are right. It does what it can - as it was said, it can't "change current behavior"! So fix tried not to change permission for files which already have right permissions and reduce amount of errors by this.
(also it fixed that size of images was unnecessarily big because of adding same file to several layers - in https://github.com/sclorg/s2i-python-container/issues/178#issuecomment-289925548)

Solution would be not to try to change files outside of `/opt/app-root/`. But this fix can't be done :-(

Another solution would be to suppress all error messages, but this could also hide real problems.

@bparees @GrahamDumpleton @pkubatrh Opinions?

**Comment by pkubatrh** [comment]
>Another solution would be to suppress all error messages, but this could also hide real problems.

I also do not like suppressing all of the possible errors. But if we do not have any means to fix this without changing the current behaviour we might have to do just that.

**Comment by GrahamDumpleton** [comment]
Can the ``find`` commands be modified to only attempt to change group or permissions if the user running the find command is the owner of the file? Would that cover all cases adequately?

If not, this is where the C code based version would be more adaptable, as it could check whether for the user it is running as, whether it would succeed and not attempt the operation, or ignore the failure in just the case where not owner and not output an error message.

**Comment by omron93** [comment]
> Can the find commands be modified to only attempt to change group or permissions if the user running the find command is the owner of the file?

Basically, yes. It can process only files owned by some users...

> Would that cover all cases adequately?

@GrahamDumpleton @bparees `s2i build` always changes owner of files provided by user?

If yes, I see no problem with this. Only it doesn't make sense to me to follow symlinks outside of `/opt/app-root`... because there are probably no files owned by default/random user. But no problem with this.

**Comment by bparees** [comment]
> I also do not like suppressing all of the possible errors. But if we do not have any means to fix this without changing the current behaviour we might have to do just that.

suppressing this error might be ok though (what does "-f" suppress?).  The purpose of this fix-permission logic is to ensure that if the user rsh's into the pod (or rsyncs files into the pod), they have sufficient permissions to update/change/delete the files (so they can make hot changes to the running pod).

If something goes wrong in fix-permissions, they won't be affected unless they are trying to manipulate the file in question and at that point we can certainly do further investigation of why that particular file did not get updated properly.

> s2i build always changes owner of files provided by user?

yes

**Comment by omron93** [comment]
> uppressing this error might be ok though (what does "-f" suppress?). The purpose of this fix-permission logic is to ensure that if the user rsh's into the pod (or rsyncs files into the pod), they have sufficient permissions to update/change/delete the files (so they can make hot changes to the running pod).

@bparees  So you vote for suppressing all warning instead of changing only files which current user owns?

>  at that point we can certainly do further investigation of why that particular file did not get updated properly.

Warning can make this easier ;-)

**Comment by bparees** [comment]
> @bparees So you vote for suppressing all warning instead of changing only files which current user owns?

i guess so.  but we should definitely get some other opinions.  this is clearly a complex subject :)

**Comment by omron93** [comment]
I've prepared #126 which tries to change permission only on files which user owns. 
And #127 which hides all error messages.

So @GrahamDumpleton @hhorak @pkubatrh @praiskup What is better from your point of view?

**Comment by pkubatrh** [comment]
>What is better from your point of view?

I still do not like masking the failures. As Ben points out - it might be harmless, but in case it is not and it does in the end mask some real problems we will have a slightly more difficult time investigating it.
So +1 for #126 from me. Still the best thing would be to just ignore everything outside of `/opt/app-root` if we could afford it.

**Comment by praiskup** [comment]
@pkubatrh wrote:
> So +1 for #126 from me. Still the best thing would be to just ignore everything outside of /opt/app-root if we could afford it.

Seconded; not crossing the borders through symlinks would sound more solid/safe fix, maybe some day ...

**Comment by hhorak** [comment]
I'd say let's give it another try (fix it without suppressing all warnings) and if it doesn't work in some cases, we can still revisit it and start suppressing them..

**Comment by pkubatrh** [comment]
>I'd say let's give it another try (fix it without suppressing all warnings) and if it doesn't work in some cases, we can still revisit it and start suppressing them..

Makes sense to me.
As there are more people in favour of #126 I will merge that one once the tests pass.
