### ISSUE TITLE
Oracle libraries require libaio.

### ISSUE THREAD

**Issue by torsava** [sclorg/s2i-base-container#140]
Moving here an issue by @GrahamDumpleton from sclorg/s2i-python-container#205.

The Linux async io library libaio is not part of the image which means that if someone installs Oracle client libraries themselves as part of a custom ``assemble`` wrapper script in order to install ``cx_Oracle`` Python client package, then it all fails.

* https://stackoverflow.com/questions/45180023/wget-curl-binaries-onto-openshift-before-dependencies-installation

The common base image should perhaps be updated to install libaio as there shouldn't be any impediment for using client libraries for any of the major database products, even if the user has to install the database libraries themselves as is case for Oracle.

**Comment by frenzymadness** [comment]
I've tested this in ubi8 container with Python 3.6 and it seems that cx-Oracle package is installable from PyPI without libaio being present on the system.

I'm closing this very old issue now. If you are still interested in it, feel free to reopen it and provide a reproducer for the problem, please.
