### ISSUE TITLE
go-md2man dependency breaks s2i-base build on rhel7

### ISSUE THREAD

**Issue by nnachefski** [sclorg/s2i-base-container#142]
### get and install the s2i tool
wget https://github.com/openshift/source-to-image/releases/download/v1.1.8/source-to-image-v1.1.8-e3140d01-linux-386.tar.gz
tar -xzvf source-to-image-v1.1.8-e3140d01-linux-386.tar.gz 
cp s2i /usr/bin

yum -y install libtool

### git clone the s2i base 
cd ~
git clone https://github.com/sclorg/s2i-base-container.git
cd s2i-base-container
git submodule update --init
make build VERSIONS=core TARGET=rhel7

> mkdir -p core/root
> go-md2man -in "core/README.md" -out "core/root/help.1"
> /bin/sh: **go-md2man: command not found**
> 
> yum provides go-md2man
> No matches found

### I want to build custom s2i images on RHEL7.  I dont want to tell the customer to install a CentOS box just to do s2i builds.

**Comment by praiskup** [comment]
go-md2man is a part of optional channel, so you need to enable rhel-7-server-optional (depends on your rhel variant). See https://access.redhat.com/documentation/en-us/red_hat_subscription_management/1/html/rhsm/supplementary-repos

**Comment by pkubatrh** [comment]
As @praiskup points out go-md2man is available on rhel7, no need to do builds on a CentOS machine.
