### ISSUE TITLE
s2i-core unavailabe in Fedora registry

### ISSUE THREAD

**Issue by pkubatrh** [sclorg/s2i-base-container#144]
```
$ docker pull registry.fedoraproject.org/26/s2i-core
Using default tag: latest
Trying to pull repository registry.fedoraproject.org/26/s2i-core ... 
manifest for registry.fedoraproject.org/26/s2i-core:latest not found

```

**Comment by omron93** [comment]
It is not built yet.

Review is done - https://bugzilla.redhat.com/show_bug.cgi?id=1483351
@hhorak ? Or please give us commit rights in Pagure and I can build the image.

**Comment by pkubatrh** [comment]
s2i-core is now available in Fedora registries, so closing this issue as resolved.
