### ISSUE TITLE
Rename STI_SCRIPTS_* env vars to S2I_SCRIPTS_*

### ISSUE THREAD

**Issue by praiskup** [sclorg/s2i-base-container#145]

**Comment by omron93** [comment]
There is a comment for `STI_SCRIPTS_URL` -  ` # DEPRECATED: Use above LABEL instead, because this will be removed in future versions.`

@bparees Is this variable still used or can be removed?

**Comment by bparees** [comment]
you can remove it as long as you have the label(io.openshift.s2i.scripts-url) instead.  Current s2i will use either and it's doubtful anyone is on such an old version of s2i that it only supports sti_scripts_url.

**Comment by frenzymadness** [comment]
According to [this search](https://grep.app/search?q=STI_SCRIPTS_PATH&case=true) there are plenty of usages of these variables in dependent container images and I don't think it's worth it to change their names now.

Feel free to reopen this issue if you disagree.
