### ISSUE TITLE
Disabling all repositories in RHEL Dockerfiles is problematic

### ISSUE THREAD

**Issue by hhorak** [sclorg/s2i-base-container#148]
The cases where we need to enable different set of repositories that what we expect -- then disabling all repos is not possible. A usual trick to build RHEL dockerfiles on an unsubscribed machine is to add a different repo in the beginning of the Dockerfile. Since RHEL Dockerfiles currently disable all repos and enable just specific ones, it means the additional repo file won't be used.

A solution for this might be either of those (or both):
* disable only repos that are coming from subscription (those matching `rhel-*`)
* disable repos only when on subscribed machine (is a simple check like `[ -f /etc/pki/entitlement/*.pem ]` good enough?)

If we use both, it could look like:
```
RUN [ -f /etc/pki/entitlement/*.pem ] && yum-config-manager --disable rhel-*
```

**Comment by ktdreyer** [comment]
I'm totally a noob here... :smile: 

If this relates to subscriptions, could you run `subscription-manager repos --disable='*'
` instead of `yum-config-manager`?

**Comment by pkubatrh** [comment]
>If this relates to subscriptions, could you run subscription-manager repos --disable='*' instead of yum-config-manager?

I do not think it is possible to actually run subscription-manager inside a container.

**Comment by omron93** [comment]
Description how repositories are enabled in rhel containers - https://access.redhat.com/solutions/1443553

**Comment by hhorak** [comment]
Also related: https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux_atomic_host/7/single/getting_started_with_containers/index#creating_docker_images
