### ISSUE TITLE
Missing groff in core or any other way how to show s2i usage

### ISSUE THREAD

**Issue by ficap** [sclorg/s2i-base-container#155]
During making tests for `redis-container`, I found out that `s2i-core` does not include `groff` which is mandatory for testing `s2i usage`. I also investigated how other images solve this and found out that they either install it manually in certain images during build or it gets "accidentally" installed as a dependency with any other packages.
Wouldn't it be better to install `groff` in `s2i-core` as a common dependency?

I also talked to @hhorak and he thinks that `groff` is superfluous because at first we convert `README.md` to man-file and then using `groff` we convert it back to plaintext. And as we already have `README.md` inside images, wouldn't be more logical just to dump it out? What is your opinion? Which is better? Or is it better to leave it as it is?

**Comment by omron93** [comment]
>  and then using groff we convert it back to plaintext. 

It is not plaintext. It's formated.

>  What is your opinion? Which is better? Or is it better to leave it as it is?

Simple dumping README.md is IMPOV worse than current state - it's less readable.

I vote for installing `groff` in s2i-core. But I don't know how many images are currently using it.

**Comment by ficap** [comment]
https://github.com/sclorg/s2i-base-container/pull/156

**Comment by frenzymadness** [comment]
`groff-base` is available in all container images.
