### ISSUE TITLE
optimize the prepare-yum-repositories script

### ISSUE THREAD

**Issue by praiskup** [sclorg/s2i-base-container#158]
Seems like in our CI, the script costs about 3 minutes per each container version; so
for sclorg/postgresql-container/pull/242 (4 versions) it takes about 12 minutes only
on disabling/enabling repositories.

**Comment by praiskup** [comment]
Maybe this is about optimizing the VM images, dunno.  Just wanted to track this somewhere.

**Comment by pkubatrh** [comment]
Limiting the disable to only enabled repositories might help a bit.

Something along the lines of (for my box at least):
`yum-config-manager --disable $(yum repolist -v | grep Repo-id | awk '{ print $3 }' | awk -F / '{ print $1 }' | xargs)`

**Comment by praiskup** [comment]
The speedup is just awesome, so I would go for the optimization (even though
it looks a bit over-engineered).
