### ISSUE TITLE
Problem with subscription when trying to build

### ISSUE THREAD

**Issue by helio-frota** [sclorg/s2i-base-container#167]
Hi,

I have a RHEL7 installed + Red Hat developer program subscription activated.
But I'm getting the following error message:

![screenshot from 2018-04-30 16-05-46](https://user-images.githubusercontent.com/6443576/39445139-69c1933e-4c90-11e8-8b76-7d5672323862.png)

What I need to do to be able to build ?

Thanks!

**Comment by pkubatrh** [comment]
No idea what is happening on your end. I have just set up a rhel 7.5 system with Red Hat developer program subscription and had no issues building images from sclorg repositories.

Considering https://github.com/sclorg/s2i-base-container/issues/166, are you using the RH packaged Docker from extra repositories on your host?

**Comment by helio-frota** [comment]
Hi @pkubatrh.

No I'm not using extra repositories. The steps I did:

* installed RHEL7
* added the subscription
* clone s2i-base-container (this repo)
* build

You can see a "summary" screenshot here:
https://user-images.githubusercontent.com/6443576/39444550-916b1826-4c8e-11e8-8a04-e9c360cdaa31.png

thanks

**Comment by pkubatrh** [comment]
>This can be the reason of the issue?

Could be, since centos has no need for code dealing for subscription management (it has none to begin with).

**Comment by pkubatrh** [comment]
Also from the link this seems like the Docker packaged Docker. That will be a completely different beast from the RH packaged one.

**Comment by helio-frota** [comment]
@pkubatrh thanks for the information. I'm going to boot on RHEL to check this.
:+1:

**Comment by helio-frota** [comment]
@pkubatrh confirmed, thanks!

https://user-images.githubusercontent.com/6443576/39529413-01a980ae-4dfd-11e8-80d7-b1dc800a56ce.png
