### ISSUE TITLE
How to make centos-sclo-rh-source and centos-sclo-sclo repos available on ppc64le ?

### ISSUE THREAD

**Issue by sandipmgiri** [sclorg/s2i-base-container#178]
I could able to build s2i base centos based container on x86. However, while building it on ppc64le , 2 repositories (centos-sclo-rh-source and centos-sclo-sclo) are getting enabled after "centos-release-scl" dependency installation. Due to these repos, we are not able to install any other dependencies. 
Getting error - http://mirror.centos.org/centos/7/sclo/ppc64le/rh/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found

Looks like these repos are not available on ppc64le , as I was getting 404 error while accessing http://mirror.centos.org/centos/7/sclo/ppc64le/rh/repodata/repomd.xml  and for x86 its accessible http://mirror.centos.org/centos/7/sclo/x86_64/rh/repodata/repomd.xml

Please can you help us on how to make above mentioned repositories available on ppc64le ?
Thanks in advance !

**Comment by sandipmgiri** [comment]
Are there source rpms available for above mentioned repositories ,if yes then can you please share the location , so that will try building it manually on ppc64le ?

Thanks!

**Comment by hhorak** [comment]
@sandipmgiri, @pkubatrh is correct, we do not have other-than-x86_64 builds for most of the SCL, therefore we do not have repos either. However, if you want to build it yourself, the source RPMs should be the same, as the same SRPM are used for all builds in upstream (RHSCL). You can get the SRPMs from CBS, e.g.: https://cbs.centos.org/koji/buildinfo?buildID=24130

Let me also mention that ppc64le, s390x and aarch64 builds are available in the RHSCL repositories, for RHEL users (might not be your case, but worth mentioning).

**Comment by snehlatamohite** [comment]
Hi All,

Thanks for the guidance. 

We have started building postgresql-10.5 package source (https://www.postgresql.org/ftp/source/) on centos 7 ppc64le. We searched steps in the url - 
https://cbs.centos.org/kojifiles/packages/rh-postgresql10-postgresql/10.5/1.el7/data/logs/x86_64/build.log 

To resolve below issue I have removed the --disable-dependency-tracking, --with-scl options from configure command will confirm once with community as well.
configure: WARNING: unrecognized options: --disable-dependency-tracking, --with-scl

Steps - 
yum update
yum groupinstall 'Development Tools' -y
yum install wget bzip zlib-devel.ppc64le readline-devel.ppc64le
mkdir BUILD && cd BUILD/
wget https://ftp.postgresql.org/pub/source/v10.5/postgresql-10.5.tar.bz2
bunzip2 postgresql-10.5.tar.bz2
tar -xvf postgresql-10.5.tar
cd postgresql-10.5
./configure --build=ppc64le-linux-gnu --host=ppc64le-linux-gnu --program-prefix=  --prefix=/opt/rh/rh-postgresql10/root/usr --exec-prefix=/opt/rh/rh-postgresql10/root/usr --bindir=/opt/rh/rh-postgresql10/root/usr/bin --sbindir=/opt/rh/rh-postgresql10/root/usr/sbin --sysconfdir=/etc/opt/rh/rh-postgresql10 --datadir=/opt/rh/rh-postgresql10/root/usr/share --includedir=/opt/rh/rh-postgresql10/root/usr/include --libdir=/opt/rh/rh-postgresql10/root/usr/lib64 --libexecdir=/opt/rh/rh-postgresql10/root/usr/libexec --localstatedir=/var/opt/rh/rh-postgresql10 --sharedstatedir=/var/opt/rh/rh-postgresql10/lib --mandir=/opt/rh/rh-postgresql10/root/usr/share/man --infodir=/opt/rh/rh-postgresql10/root/usr/share/info pgdocdir=/opt/rh/rh-postgresql10/root/usr/share/doc/rh-postgresql10-postgresql-10.5 PGVERSION=10.5 PGMAJORVERSION=10 NAME_DEFAULT_PREV_SERVICE=postgresql
make -j32

build output is  - 
All of PostgreSQL successfully made. Ready to install.


We are basically trying to build following centOS based images on ppc64le so first we need to build the missing packages on ppc64le. Can you please redirect to build steps/build scripts used for building scl packages on centOS X86? 
2.  and which are getting deployed 
  MySQL-57, Go, LLVM, Rust
  Nodejs-8 (rhel)
  Nodejs-6 (rhel)
  Php-71  (rhel)
  Python-27
  Python-36 (rhel)
  Ruby-25
  Perl-526
  Varnish-5 (rhel)
  Apache httpd-24 (rhel)

Please do let us know if you have any suggestion or guidance.  

Thanks,
Snehlata Mohite.

**Comment by pkubatrh** [comment]
>Can you please redirect to build steps/build scripts used for building scl packages on centOS X86?

You can find it in srpms located in centos CBS (link from the example posted by @hhorak above).

You can either try to search for the components by their name, or you can use [this query](https://cbs.centos.org/koji/search?match=glob&type=tag&terms=sclo7-rh-*-release) that lists sclorg tags for each component. From the tag you can get to the actual package builds.

**Comment by qhaas** [comment]
The process of building SCL packages from src rpms in CentOS7 is made a bit painful due to the [extras ppc64le repo](https://bugs.centos.org/view.php?id=15615) not being fully functional, so one can't easily do a `yum-builddep` on the src rpm to grab the packages necessary to build.  Works fine in RHEL7.  The alternative is to extract the SPEC file and grep out the build dependencies for each src rpm; can be scripted, but could take a while to run.

While plenty of docker containers exist for running pre-built SCL programs, didn't see any for building them, which would be handy, especially if it had tooling to automatically deploy build dependencies.

**Comment by frenzymadness** [comment]
I'm gonna close this stale issue. If you still have something related to the base containers to discuss, feel free to reopen it.
