### ISSUE TITLE
Better check for subscribed host in prepare-yum-repositories

### ISSUE THREAD

**Issue by pkubatrh** [sclorg/s2i-base-container#191]
We ran into an issue recently with the existing certificate check when the built container had a cert file in the expected location but the host was not actually subscribed (no .repo file from host). This lead to building the image in "subscribed" mode and triggering #190 

According to rcerven:

>  also I am not sure how to actually check from container that underlying system is subscribed, but checking for certificate doesn't seems good way
> 
> you can't use 'subscription-manager list' in container since that will report :
> "subscription-manager is disabled when running inside a container. Please refer to your host system for subscription management."
> 
> only reliable check that I know of is : yum repolist reports only repos which were provided

**Comment by frenzymadness** [comment]
Given the fact that this script is used only for RHEL 7, which is now in the maintenance-only phase, I'd not invest our energy in improving this.
