### ISSUE TITLE
Update to Fedora 34

### ISSUE THREAD

**Issue by frenzymadness** [sclorg/s2i-base-container#203]
Is there any reason to stay with Fedora 31? If not, I can prepare an update.

**Comment by pvalena** [comment]
Bump @phracek @pkubatrh.

It's a bit outdated now. I'm testing with Fedora 34 now (literaly just replaced 31 with 34 in .fedora Dockerfiles).

Let me know if you need a PR or anything.

**Comment by pvalena** [comment]
The build: https://git.io/JqkQ6

I've noticed pre-existing `core` was used to build `base` (shouln't it be built on top of currently built core?). Rebuilt manually on top of the newly created one: https://git.io/Jqk7t

We're also trying to run s2i-ruby-container build+test suite with it - see linked issue for progress.

**Comment by frenzymadness** [comment]
Isn't it too soon for Fedora 34? I'd prefer 33 because 34 is not yet even beta.

**Comment by pkubatrh** [comment]
>Let me know if you need a PR or anything.

Will take care of this, thanks!

>I've noticed pre-existing core was used to build base (shouln't it be built on top of currently built core?).

Ideally yes. The issue here is that the freshly built s2i-core image is not tagged as `registry.fedoraproject.org/f34/s2i-core:latest`, only 1f34/s2i-core:01 and 1f34/s2i-core:latest1 and 1f34/s2i-core:20201124-f7cfc3d`. Would need a bit of changes in common scripts to make it work correctly

**Comment by pkubatrh** [comment]
>Isn't it too soon for Fedora 34? I'd prefer 33 because 34 is not yet even beta.

I am currently working on f34-based images, so this makes sense to me. I do not think we will be syncing to f33 at this point as it is released, so imo no point having it upstream.

**Comment by pvalena** [comment]
> Isn't it too soon for Fedora 34? I'd prefer 33 because 34 is not yet even beta.

Ideally, we'd have both.
This does not dictate what is built in Fedora.
Also, in Fedora, the repo has versioned branches: https://src.fedoraproject.org/container/ruby/
rawhide would be the 35 (not sure we want to build containers for that) - but we can use the branches arbitrarily.
33 is already built, used f.e. in: https://koji.fedoraproject.org/koji/buildinfo?buildID=1718180
I don't see why we'd want to "hold" the upstream to later versions.
