### ISSUE TITLE
F34 s2i-core and s2i-base: /tmp not writeable by all

### ISSUE THREAD

**Issue by jackorp** [sclorg/s2i-base-container#208]
While testing the s2i ruby container I ran into a `/tmp` dir permissions problem.

This is present in both the s2i-core and s2i-base in Fedora 34: [ruby build log with the issue](https://gist.github.com/jackorp/c73c3562483bf485660f0016b3344bac#file-gistfile1-txt-L83)

When I ran `ls -al` to see permissions on `/tmp` during build I got the following:
```console
RUN ls -al /tmp
total 0
drwxr-xr-x.  2 root root 0 Mar  4 11:29 .
dr-xr-xr-x. 18 root root 0 Mar 23 09:08 ..
```
As I understand it, the `/tmp` permissions should correctly be 777.

Dockerfile used:
```Dockerfile
FROM registry.fedoraproject.org/f34/s2i-core

RUN ls -al /tmp
```
I get the same result if I substitute `s2i-core` with `s2i-base`

**Comment by frenzymadness** [comment]
When I run base Fedora container, I get the same result, so it's probably not related to S2I images.
Rawhide:
```
[root@915226ba7517 /]# ls -la /tmp/
total 8
drwxr-xr-x.  2 root root 4096 Mar 11 08:27 .
dr-xr-xr-x. 18 root root 4096 Mar 25 08:32 ..
```
F34:
```
[root@f4effff8169a /]# ls -la /tmp/
total 8
drwxr-xr-x.  2 root root 4096 Mar 23 10:24 .
dr-xr-xr-x. 18 root root 4096 Mar 25 08:34 ..
```
But F33 has different permissions. 
```
[root@df3f780c1404 /]# ls -la /tmp/
total 12
drwxrwxrwt.  2 root root 4096 Jan  6 07:48 .
dr-xr-xr-x. 18 root root 4096 Mar 25 08:40 ..
-rwx------.  1 root root  757 Jan  6 07:48 ks-script-ai1xyg9g
```
This might be something worth reporting. I have no idea why this is different.

**Comment by phracek** [comment]
What about reporting it into fedora devel and check why it was changed.
Maybe we should change it to different location. But this is a guess :)

**Comment by frenzymadness** [comment]
Reported: https://pagure.io/ContainerSIG/container-sig/issue/49

**Comment by frenzymadness** [comment]
This issue is fixed in the latest f34 and rawhide images, see the bug report mentioned above for more details. A workaround is reinstalling the filesystem package which fixes the permissions. I'm closing the issue. Feel free to reopen it or comment on pagure.
