### ISSUE TITLE
Replace CentOS 8 with AlmaLinux 8

### ISSUE THREAD

**Issue by srbala** [sclorg/s2i-base-container#250]
Team has any plans to consider replace CentOS 8 with AlmaLinux 8. 

If team accepts this proposal, I would happy contribute

**Comment by pkubatrh** [comment]
Hi @srbala 
No, currently no plans to replace Centos 8 with AlmaLinux 8. We do have an open PR for building the s2i-core and s2i-base images from Centos Stream 8 however:  #246

**Comment by frenzymadness** [comment]
There are currently three different levels of container images: Fedora → Centos stream → RHEL/UBI. Given the fact that we support all of them and that also RHEL/UBI is available for free, we don't have the motivation to support also clones of RHEL.

Feel free to reopen the issue if you think I'm missing something or if I'm wrong.
