### ISSUE TITLE
Fedora 36

### ISSUE THREAD

**Issue by frenzymadness** [sclorg/s2i-base-container#253]
Fedora 36 is out so we can update. There is no rush as Fedora 35 EOL will be in November. From Python perspective, Fedora 36 still has Python 3.10 as the main Python interpreter so there is currently no reason for updating. What about other images?

**Comment by phracek** [comment]
Good, question. Update to Fedora 36 could be done slowly, but this version contained several versions which are not ready in containers yet;) Like Perl-5.34. Nowadays we have only Perl-5.32 for C9S and Fedora soon.

But we can definitely update s2i-core and s2i-base to Fedora 36. Nothing against it.
